
tasks:
  - init: |
      go install golang.org/dl/go1.18beta2@latest
      go1.18beta2 download
      go1.18beta2 version
      alias go=go1.18beta2=
      go version
    command: |
      echo "Hello"
vscode:
  extensions:
    - golang.go
